### ISSUE TITLE
TypeError in Safari 9.1.2

### ISSUE THREAD

**Issue by marco-a** [pladaria/reconnecting-websocket#3]
I get a `TypeError: WebSocket constructor not set. Set "options.constructor"` error message in Safari 9.1.2 (11601.7.7) when using browserify 13.1.0 and reconnecting-websocket.

Test to reproduce:

`browserify -r reconnecting-websocket:websocket > websocket.js`

```
<!DOCTYPE HTML>
<html>
<head>
<script src="websocket.js" type="text/javascript"></script>
</head>
<body>
<script>
    var websocket = require('websocket');

    var ws = new websocket('ws://localhost:1337');
</script>
</body>
</html>
```

OS I'm using is Mac OS X 10.11.6 (15G31) El Capitan.

**Comment by pladaria** [comment]
Thanks for reporting. It seems that in safari `typeof WebSocket === 'object'` while in other browsers `typeof WebSocket === 'function'`. Will fix that asap

**Comment by pladaria** [comment]
The issue should be fixed. Please, ping me if you have any problems.

Thanks!

**Comment by juice49** [comment]
Hi, still seems to be a problem with this. Apologies, I'm currently debugging the built code, I'll try and fix in the source and PR later.

The problem is old Safari reports `typeof WebSocket` as "object", not "function". This fails the check in line 63 of the built code:

```
if (typeof config.constructor !== 'function') {
  throw new TypeError('WebSocket constructor not set. Set `options.constructor`');
}
```

You can recreate this on desktop if you use the stable Safari version (Safari Tech Preview reports `typeof WebSocket` as "function').

**Comment by marco-a** [comment]
It is not working for me either.

**Comment by pladaria** [comment]
I've published a new package: 1.4.3
Thanks for the feedback!

**Comment by juice49** [comment]
@pladaria Looks like the new version didn't make it to npm, latest version is 1.4.0.

**Comment by pladaria** [comment]
Published again.
Sorry for the inconveniences.

**Comment by juice49** [comment]
Thanks!

**Comment by Gladkov-Art** [comment]
Doesn't work for me. Still have the same issue. React-native 0.30.0 and reconnecting-websocket 1.4.3

**Comment by pladaria** [comment]
Published 1.4.4 which fixes WebSocket detection for ReactNative
Tested using React Native 0.31.0 (iOS)

Thanks for your feedback
